[package]
name = "janus-event-api"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Event handler API trait definitions for Janus Gateway"

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
janus-plugin-api.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
